name: ⚡ 빠른 수정 요청
description: 간단한 수정사항을 빠르게 요청합니다 (한 줄 설명만으로 OK!)
title: "[빠른수정] "
labels: ["quick-fix", "auto-fix"]
assignees:
  - qws941

body:
  - type: markdown
    attributes:
      value: |
        ## ⚡ 빠른 수정 요청
        
        간단한 한 줄 설명만으로 Claude가 자동 수정합니다!
        
        **예시:**
        - "REGTECH 수집이 안 돼요"
        - "블랙리스트 페이지가 느려요" 
        - "에러 메시지가 한글로 나와야 해요"
        - "다크모드에서 글자가 안 보여요"
        
        ---

  - type: textarea
    id: quick-description
    attributes:
      label: 🎯 무엇을 수정해달라고 하시나요?
      description: 한 줄로 간단히 설명해주세요. Claude가 자동으로 분석합니다!
      placeholder: 예) "REGTECH 로그인이 안 돼요" 또는 "블랙리스트 조회가 너무 느려요"
    validations:
      required: true

  - type: checkboxes
    id: quick-consent
    attributes:
      label: 🤖 자동 처리 동의
      options:
        - label: Claude가 자동으로 수정하는 것에 동의합니다
          required: true